name: Test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn --frozen-lockfile
      - name: Extract base commit
        shell: bash
        run: echo "##[set-output name=commit;]$(git rev-parse ${{ github.base_ref }})"
        id: extract_commit
      - run: yarn precise-commits --whitelist="packages/**/*.ts" --check-only --head=$GITHUB_SHA --base=${{ steps.extract_commit.outputs.commit }}
      - run: yarn test
        env:
          CI: true
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          name: codecov-connect
          fail_ci_if_error: true
